package ru.ubrr.component;

public final class AliasConstants {
	public static final String ADAPTER = "Adapter";
	public static final String VKL = "VKL";
	public static final String SERVICE = "service";
	public static final String ADAPTER_SERVICE = ADAPTER + " " + SERVICE;
	public static final String VKL_SERVICE = VKL + " " + SERVICE;
	public static final String START_REQUEST_FOR_PARTNER = "starting request for partner";
	
	public static final String END_REQUEST_FOR_PARTNER = "complete request for partner";
	public static final String WITH_RESULT = "with result";
	
			

	public final static String CALL_0_CALL_1 = "CALL_0/CALL_1";
	public final static String CHECK_LIMIT_STATUS = "Check Limit Status";
	public final static String ADVANCED_LIMIT_CALCULATION = "Advanced Limit Calculation";
	public final static String FINAL_LIMIT_CALCULATION = "Final Limit Calculation";
	
	public static final String VKL_SERVICE_CALL_0_CALL_1_START_REQUEST_FOR_PARTNER = VKL_SERVICE +" "+CALL_0_CALL_1+ ": " + START_REQUEST_FOR_PARTNER+ " {}";
	public static final String VKL_SERVICE_CALL_0_CALL_1_END_REQUEST_FOR_PARTNER_WITH_RESULT = VKL_SERVICE +" "+CALL_0_CALL_1+ ": " + END_REQUEST_FOR_PARTNER +" {} "+WITH_RESULT +": {}";
	public static final String ADAPTER_SERVICE_CALL_0_CALL_1_START_REQUEST_FOR_PARTNER = ADAPTER_SERVICE +" "+CALL_0_CALL_1+ ": " + START_REQUEST_FOR_PARTNER+ " {}";
	public static final String ADAPTER_SERVICE_CALL_0_CALL_1_END_REQUEST_FOR_PARTNER_WITH_RESULT = ADAPTER_SERVICE +" "+CALL_0_CALL_1+ ": " + END_REQUEST_FOR_PARTNER +" {} "+WITH_RESULT +": {}";

	public static final String VKL_SERVICE_CHECK_LIMIT_STATUS_START_REQUEST_FOR_PARTNER = VKL_SERVICE +" "+CHECK_LIMIT_STATUS+ ": " + START_REQUEST_FOR_PARTNER	+ " {}";
	public static final String VKL_SERVICE_CHECK_LIMIT_STATUS_END_REQUEST_FOR_PARTNER_WITH_RESULT = VKL_SERVICE +" "+CHECK_LIMIT_STATUS+ ": " + END_REQUEST_FOR_PARTNER +" {} "+WITH_RESULT +": {}";
	public static final String ADAPTER_SERVICE_CHECK_LIMIT_STATUS_START_REQUEST_FOR_PARTNER = ADAPTER_SERVICE +" "+CHECK_LIMIT_STATUS+ ": " + START_REQUEST_FOR_PARTNER+ " {}";
	public static final String ADAPTER_SERVICE_CHECK_LIMIT_STATUS_END_REQUEST_FOR_PARTNER_WITH_RESULT = ADAPTER_SERVICE +" "+CHECK_LIMIT_STATUS+ ": " + END_REQUEST_FOR_PARTNER +" {} "+WITH_RESULT +": {}";
	
	public static final String VKL_SERVICE_ADVANCED_LIMIT_CALCULATION_START_REQUEST_FOR_PARTNER = VKL_SERVICE +" "+ADVANCED_LIMIT_CALCULATION+ ": " + START_REQUEST_FOR_PARTNER	+ " {}";
	public static final String VKL_SERVICE_ADVANCED_LIMIT_CALCULATION_END_REQUEST_FOR_PARTNER_WITH_RESULT = VKL_SERVICE +" "+ADVANCED_LIMIT_CALCULATION+ ": " + END_REQUEST_FOR_PARTNER +" {} "+WITH_RESULT +": {}";
	public static final String ADAPTER_SERVICE_ADVANCED_LIMIT_CALCULATION_START_REQUEST_FOR_PARTNER = ADAPTER_SERVICE +" "+ADVANCED_LIMIT_CALCULATION+ ": " + START_REQUEST_FOR_PARTNER+ " {}";
	public static final String ADAPTER_SERVICE_ADVANCED_LIMIT_CALCULATION_END_REQUEST_FOR_PARTNER_WITH_RESULT = ADAPTER_SERVICE +" "+ADVANCED_LIMIT_CALCULATION+ ": " + END_REQUEST_FOR_PARTNER +" {} "+WITH_RESULT +": {}";

	public static final String VKL_SERVICE_FINAL_LIMIT_CALCULATION_START_REQUEST_FOR_PARTNER = VKL_SERVICE +" "+FINAL_LIMIT_CALCULATION+ ": " + START_REQUEST_FOR_PARTNER	+ " {}";
	public static final String VKL_SERVICE_FINAL_LIMIT_CALCULATION_END_REQUEST_FOR_PARTNER_WITH_RESULT = VKL_SERVICE +" "+FINAL_LIMIT_CALCULATION+ ": " + END_REQUEST_FOR_PARTNER +" {} "+WITH_RESULT +": {}";
	public static final String ADAPTER_SERVICE_FINAL_LIMIT_CALCULATION_START_REQUEST_FOR_PARTNER = ADAPTER_SERVICE +" "+FINAL_LIMIT_CALCULATION+ ": " + START_REQUEST_FOR_PARTNER+ " {}";
	public static final String ADAPTER_SERVICE_FINAL_LIMIT_CALCULATION_END_REQUEST_FOR_PARTNER_WITH_RESULT = ADAPTER_SERVICE +" "+FINAL_LIMIT_CALCULATION+ ": " + END_REQUEST_FOR_PARTNER +" {} "+WITH_RESULT +": {}";

}
